# Generated by Django 5.1.4 on 2025-01-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
